CREATE TABLE `country_code` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL COMMENT '中文名称',
  `en_name` VARCHAR(64) NOT NULL COMMENT '国际名称',
  `en_code` VARCHAR(10) NULL COMMENT '国际简码',
  `country_code` VARCHAR(10) NOT NULL COMMENT '国家地区代码',
  `sms_code` VARCHAR(10) NOT NULL COMMENT '短信国际代码',
  `sms_price` FLOAT NOT NULL COMMENT '短信价格',
  `status` TINYINT(2) NOT NULL DEFAULT 1 COMMENT '是否启用',
  PRIMARY KEY (`id`),
  INDEX `country_code` (`country_code` ASC))
  COMMENT = '国家编码';

### 从创蓝获取短信国际编号xls文件
# $filename = 'country_code.xls';
# $spreadsheet = IOFactory::load($filename);
# $worksheet = $spreadsheet->getActiveSheet();
# $insert = 'INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price` ) VALUES ("%s","%s","%s","%s","%s","%s");';
#
# foreach ($worksheet->getRowIterator() as $row) {
#     $ridx = $row->getRowIndex();
#     $enName = $worksheet->getCellByColumnAndRow(1, $ridx)->getValue();
#     $name = $worksheet->getCellByColumnAndRow(2, $ridx)->getValue();
#     $enCode = $worksheet->getCellByColumnAndRow(3, $ridx)->getValue();
#     $smsCode = $worksheet->getCellByColumnAndRow(4, $ridx)->getValue();
#     $price = $worksheet->getCellByColumnAndRow(5, $ridx)->getValue();
#
#     $s = sprintf($insert, $name, $enName, $enCode, intval($smsCode), trim($smsCode), $price);
#     echo $s . PHP_EOL;
# }

INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("安哥拉","Angola","AO","244","00244","0.546", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("阿富汗","Afghanistan","AF","93","0093","0.623", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("阿尔巴尼亚","Albania","AL","355","00355","0.321", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("阿尔及利亚","Algeria","DZ","213","00213","0.963", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("安道尔共和国","Andorra","AD","376","00376","0.182", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("安圭拉岛","Anguilla","AI","1264","001264","0.481", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("安提瓜和巴布达","Antigua and Barbuda","AG","1268","001268","0.481", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("阿根廷","Argentina","AR","54","0054","0.257", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("亚美尼亚","Armenia","AM","374","00374","0.401", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("阿森松","Ascension","","247","00247","1", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("澳大利亚","Australia","AU","61","0061","0.498", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("奥地利","Austria","AT","43","0043","0.899", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("阿塞拜疆","Azerbaijan","AZ","994","00994","1.164", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("巴哈马","Bahamas","BS","1242","001242","0.241", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("巴林","Bahrain","BH","973","00973","0.289", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("孟加拉国","Bangladesh","BD","880","00880","0.722", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("巴巴多斯","Barbados","BB","1246","001246","0.481", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("白俄罗斯","Belarus","BY","375","00375","0.144", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("比利时","Belgium","BE","32","0032","0.562", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("伯利兹城","Belize","BZ","501","00501","0.321", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("贝宁","Benin","BJ","229","00229","0.642", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("百慕大","Bermuda","BM","1441","001441","0.321", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("玻利维亚","Bolivia","BO","591","00591","0.835", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("博茨瓦纳","Botswana","BW","267","00267","0.802", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("巴西","Brazil","BR","55","0055","0.225", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("文莱达鲁萨兰国","Brunei Darussalam","BN","673","00673","0.321", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("保加利亚","Bulgaria","BG","359","00359","0.899", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("布基纳法索","Burkina Faso","BF","226","00226","0.321", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("缅甸","Myanmar","MM","95","0095","0.963", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("布隆迪","Burundi","BI","257","00257","1.123", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("喀麦隆","Cameroon","CM","237","00237","0.642", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("加拿大","Canada","CA","1","001","0.193", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("开曼群岛","Cayman Islands","KY","1345","001345","0.481", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("中非共和国","Central African Republic","CF","236","00236","0.385", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("乍得","Chad","TD","235","00235","0.401", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("智利","Chile","CL","56","0056","0.53", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("中国","China","CN","86","0086","0.06", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("哥伦比亚","Colombia","CO","57","0057","0.27", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("刚果","Congo","CG","242","00242","0.691", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("库克群岛","Cook Islands","CK","682","00682","0.385", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("哥斯达黎加","Costa Rica","CR","506","00506","0.433", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("古巴","Cuba","CU","53","0053","0.225", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("塞浦路斯","Cyprus","CY","357","00357","0.722", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("捷克","Czech Republic","CZ","420","00420","0.594", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("丹麦","Denmark","DK","45","0045","0.257", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("吉布提","Djibouti","DJ","253","00253","1.059", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("厄瓜多尔","Ecuador","EC","593","00593","1.284", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("埃及","Egypt","EG","20","0020","0.481", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("萨尔瓦多","El Salvador","SV","503","00503","0.481", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("爱沙尼亚","Estonia","EE","372","00372","0.642", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("埃塞俄比亚","Ethiopia","ET","251","00251","0.321", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("斐济","Fiji","FJ","679","00679","0.562", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("芬兰","Finland","FI","358","00358","0.658", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("法国","France","FR","33","0033","0.77", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("法属圭亚那","French Guiana","GF","594","00594","1.284", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("加蓬","Gabon","GA","241","00241","0.337", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("冈比亚","Gambia","GM","220","00220","0.385", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("格鲁吉亚","Georgia","GE","995","00995","1.123", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("德国","Germany","DE","49","0049","0.498", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("加纳","Ghana","GH","233","00233","0.562", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("直布罗陀","Gibraltar","GI","350","00350","0.305", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("希腊","Greece","GR","30","0030","0.61", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("格林纳达","Grenada","GD","1473","001473","0.481", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("关岛","Guam","GU","1671","001671","1.284", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("危地马拉","Guatemala","GT","502","00502","0.642", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("几内亚","Guinea","GN","224","00224","1.123", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("圭亚那","Guyana","GY","592","00592","0.514", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("海地","Haiti","HT","509","00509","0.802", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("洪都拉斯","Honduras","HN","504","00504","0.321", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("香港（中国）","Hong Kong（China）","HK","852","00852","0.4", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("匈牙利","Hungary","HU","36","0036","0.706", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("冰岛","Iceland","IS","354","00354","0.401", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("印度","India","IN","91","0091","0.161", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("印度尼西亚","Indonesia","ID","62","0062","0.353", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("伊朗（伊斯兰共和国）","Iran (Islamic Republic of)","IR","98","0098","1.123", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("伊拉克","Iraq","IQ","964","00964","0.802", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("爱尔兰","Ireland","IE","353","00353","0.61", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("以色列","Israel","IL","972","00972","0.289", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("意大利","Italy","IT","39","0039","0.61", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("牙买加","Jamaica","JM","1876","001876","0.481", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("日本","Japan","JP","81","0081","0.577", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("约旦","Jordan","JO","962","00962","0.241", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("柬埔寨","Cambodia","KH","855","00855","0.374", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("哈萨克","Kazakhstan","KZ","7","007","0.321", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("肯尼亚","Kenya","KE","254","00254","0.193", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("韩国","South Korea","KR","82","0082","0.514", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("科威特","Kuwait","KW","965","00965","0.61", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("吉尔吉斯","Kyrgyzstan","KG","996","00996","0.321", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("老挝","Lao People's Democratic Republic","LAO","856","00856","0.514", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("拉脱维亚","Latvia","LV","371","00371","0.498", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("黎巴嫩","Lebanon","LB","961","00961","0.385", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("莱索托","Lesotho","LS","266","00266","0.385", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("利比里亚","Liberia","LR","231","00231","0.963", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("利比亚","Libyan Arab Jamahiriya","LY","218","00218","0.514", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("列支敦士登","Liechtenstein","LI","423","00423","0.401", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("立陶宛","Lithuania","LT","370","00370","0.177", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("卢森堡","Luxembourg","LU","352","00352","0.385", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("澳门（中国）","Macau（China）","MO","853","00853","0.562", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("马达加斯加","Madagascar","MG","261","00261","0.401", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("马拉维","Malawi","MW","265","00265","0.481", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("马来西亚","Malaysia","MY","60","0060","0.562", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("马尔代夫","Maldives","MV","960","00960","0.162", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("马里","Mali","ML","223","00223","0.337", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("马尔他","Malta","MT","356","00356","0.321", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("北马里亚纳群岛","Northern Mariana Islands","MP","1670","001670","0.491", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("马提尼克岛","Martinique","MQ","596","00596","1.284", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("毛里求斯","Mauritius","MU","230","00230","1.123", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("墨西哥","Mexico","MX","52","0052","0.321", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("摩尔多瓦","Moldova","MD","373","00373","0.883", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("摩纳哥","Monaco","MC","377","00377","0.481", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("外蒙古","Mongolia","MN","976","00976","0.481", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("蒙特塞拉特","Montserrat","MS","1664","001664","0.241", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("摩洛哥","Morocco","MA","212","00212","0.562", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("莫桑比克","Mozambique","MZ","258","00258","0.481", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("那米比亚","Namibia","NA","264","00264","0.53", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("瑙鲁","Nauru","NR","674","00674","0.481", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("尼泊尔","Nepal","NP","977","00977","0.883", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("荷兰安的列斯群岛","Netherlands Antilles","AN","599","00599","0.46", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("荷兰","Netherlands","NL","31","0031","0.802", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("新西兰","New Zealand","NZ","64","0064","0.963", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("尼加拉瓜","Nicaragua","NI","505","00505","0.401", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("尼日尔","Niger","NE","227","00227","1.204", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("尼日利亚","Nigeria","NG","234","00234","0.481", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("朝鲜","North Korea","KP","850","00850","0.514", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("挪威","Norway","NO","47","0047","0.514", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("阿曼","Oman","OM","968","00968","0.337", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("巴基斯坦","Pakistan","PK","92","0092","0.225", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("巴拿马","Panama","PA","507","00507","0.481", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("巴布亚新几内亚","Papua New Guinea","PG","675","00675","0.401", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("巴拉圭","Paraguay","PY","595","00595","0.289", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("秘鲁","Peru","PE","51","0051","0.353", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("菲律宾共和国","Philippines","PH","63","0063","0.241", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("波兰","Poland","PL","48","0048","0.321", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("法属玻里尼西亚","French Polynesia","PF","689","00689","0.797", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("葡萄牙","Portugal","PT","351","00351","0.385", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("波多黎各","Puerto Rico","PR","1787","001787","0.369", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("卡塔尔","Qatar","QA","974","00974","0.417", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("留尼汪岛","Reunion","RE","262","00262","0.537", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("罗马尼亚","Romania","RO","40","0040","1.123", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("俄罗斯联邦","Russian Federation","RU","7","007","0.321", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("圣卢西亚岛","Santa Luzia Island","LCA","1758","001758","0.46", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("圣文森特和格林纳丁斯","Saint Vincent and the Grenadines","VCT","1784","001784","0.481", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("东萨摩亚(美)","Samoa Eastern","","684","00684","0.77", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("美属萨摩亚","Samoa","WS","685","00685","0.642", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("圣马力诺共和国","San Marino","SM","378","00378","0.802", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("圣多美和普林西比","Sao Tome and Principe","STP","239","00239","0.642", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("沙特阿拉伯","Saudi Arabia","SA","966","00966","0.337", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("塞内加尔","Senegal","SN","221","00221","0.722", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("塞舌尔","Seychelles","SC","248","00248","0.369", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("塞拉利昂","Sierra Leone","SL","232","00232","1.123", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("新加坡","Singapore","SG","65","0065","0.414", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("斯洛伐克（斯洛伐克人的共和国）","Slovakia (Slovak Republic)","SK","421","00421","0.498", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("斯洛文尼亚","Slovenia","SI","386","00386","0.257", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("索罗门群岛","Solomon Islands","SB","677","00677","0.321", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("索马里","Somalia","SO","252","00252","0.899", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("南非","South Africa","ZA","27","0027","0.321", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("西班牙","Spain","ES","34","0034","0.963", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("斯里兰卡","Sri Lanka","LK","94","0094","0.321", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("苏丹","Sudan","SD","249","00249","1.123", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("苏里南","Suriname","SR","597","00597","0.642", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("斯威士兰","Swaziland","SZ","268","00268","0.401", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("瑞典","Sweden","SE","46","0046","0.754", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("瑞士","Switzerland","CH","41","0041","0.546", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("叙利亚","Syrian Arab Republic","SY","963","00963","0.899", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("台湾（中国）","Taiwan（China）","TW","886","00886","0.46", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("塔吉克","Tajikistan","TJ","992","00992","0.209", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("坦桑尼亚","Tanzania","TZ","255","00255","1.123", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("泰国","Thailand","TH","66","0066","0.241", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("多哥","Togo","TG","228","00228","0.417", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("汤加","Tonga","TO","676","00676","0.562", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("特立尼达和多巴哥","Trinidad and Tobago","TT","1868","001868","0.481", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("突尼斯","Tunisia","TN","216","00216","0.883", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("土耳其","Turkey","TR","90","0090","0.923", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("土库曼","Turkmenistan","TM","993","00993","0.144", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("乌干达","Uganda","UG","256","00256","0.551", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("乌克兰","Ukraine","UA","380","00380","0.225", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("阿拉伯联合酋长国","United Arab Emirates","AE","971","00971","0.378", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("英国","United Kingdom","UK","44","0044","0.449", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("美国","United States","US","1","001","0.193", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("乌拉圭","Uruguay","UY","598","00598","0.514", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("乌兹别克斯坦","Uzbekistan","UZ","998","00998","0.786", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("委内瑞拉","Venezuela","VE","58","0058","0.289", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("越南","Vietnam","VN","84","0084","0.562", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("也门","Yemen","YE","967","00967","0.433", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("南斯拉夫","Yugoslavia","YU","381","00381","0.245", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("津巴布韦","Zimbabwe","ZW","263","00263","0.385", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("赞比亚","Zambia","ZM","260","00260","0.305", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("迪戈加西亚岛 ","Diego Garcia","","246","00246","1.123", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("阿鲁巴","Aruba","aw","297","00297","0.481", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("不丹","Bhutan","BT","975","00975","1.123", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("波斯尼亚和黑塞哥维那","Bosnia and Herzegovina","BA","387","00387","0.241", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("佛得角","Cape Verde","CV","238","00238","0.963", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("科摩罗","Comoros","KM","269","00269","0.578", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("刚果民主共和国","Congo, The Democratic Republic Of The","ZR","243","00243","1.074", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("克罗地亚","Croatia (local name: Hrvatska)","HR","385","00385","0.642", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("赤道几内亚","Equatorial Guinea","GQ","240","00240","0.321", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("福克兰群岛","Falkland Islands (Malvinas)","FK","500","00500","0.241", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("法罗群岛","Faroe Islands","FO","298","00298","0.321", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("格陵兰","Greenlandcode","GL","45","0045","0.257", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("瓜德罗普岛","Guadeloupe","GP","590","00590","1.284", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("几内亚比绍","Guinea-Bissau","GW","245","00245","0.642", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("马其顿","The Republic of Macedonia","MKD","389","00389","0.225", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("毛里塔尼亚","Mauritania","MR","222","00222","1.123", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("密克罗尼西亚","Micronesia","FM","691","00691","0.642", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("黑山共和国","Montenegro","MNE","382","00382","0.225", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("新喀里多尼亚","New Caledonia","NC","687","00687","0.851", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("诺福克岛","Norfolk Island","NF","6723","006723","0.722", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("帛琉","Palau","PW","680","00680","0.241", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("巴勒斯坦","Palestine","PS","970","00970","0.401", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("卢旺达","Rwanda","RW","250","00250","0.353", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("圣基茨和尼维斯","The Federation of Saint Kitts and Nevis","KNA","1869","001869","0.481", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("塞尔维亚共和国","Serbia","SRB","381","00381","0.245", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("南苏丹共和国","The Republic of South Sudan","SSD","211","00211","0.642", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("瓦努阿图","Vanuatu","VU","678","00678","0.562", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("Cote D'Ivoire","Cote D'Ivoire","CI","225","00225","0.642", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("多米尼克国","Dominica","DM","1767","001767","0.46", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("东帝汶","East Timor","TP","670","00670","1.123", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("厄立特里亚国","Eritrea","ER","291","00291","3.21", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("沃利斯和富图纳群岛","Wallis And Futuna Islands","WF","681","00681","1.21", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("维尔京群岛(美国)","Virgin Islands (U.S.)","VI","1340","001340","0.481", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("图瓦卢","Tuvalu","TV","688","00688","1.21", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("土克斯及开科斯群岛","Turks and Caicos Islands","TC","1809","001809","0.481", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("托克劳","Tokelau","TK","690","00690","1.21", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("马绍尔群岛","Marshall Islands","MH","692","00692","1.21", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("基里巴斯","Kiribati","KIR","686","00686","1", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("夏威夷","Hawaii","","1808","001808","1", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("圣皮埃尔岛及密克隆岛","San.Pierre And Miquelon I.","SPM","508","00508","1", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("纽埃","Niue I. ","NIU","683","00683","1", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("圣赫勒拿 ","St.Helena ","SHN","290","00290","1", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("梵蒂冈(罗马教廷)","Vatican City State (Holy See)","VA","39","0039","0.61", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("威克岛(美)","Wake I.","","1808","001808","1", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("阿布哈兹","the Republic of Abkhazia","ABH","7","007","0.321", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("萨摩亚","American Samoa","AS","684","00684","0.77", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("泽西岛","Bailiwick of Jersey","BJ","44","0044","0.449", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("科科斯群岛","Cocos (Keeling) Islands","CC","61","0061","0.498", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("圣延岛","Christmas Island","CX","61","0061","0.498", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("西撒哈拉","Western Sahara","EH","685","00685","0.642", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("法国大都会","France Metropolitan","FX","33","0033","0.77", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("英属印度洋领地","British Indian Ocean Territory","IO","246","00246","1.123", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("皮特凯恩岛","Pitcairn","PN","64","0064","0.963", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("南奥赛梯","the Republic of South Ossetia","SO","7","007","0.321", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("圣马丁岛","Saint Martin","SX","590","00590","1.284", 1);
INSERT INTO `country_code` (`name`, `en_name`, `en_code`, `country_code`, `sms_code`, `sms_price`, `status`) VALUES ("马约特","Mayotte","YT","262","00262","0.537", 1);
