CREATE TABLE `ai_play_record` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `student_id` int(11) NOT NULL COMMENT '学生id',
  `lesson_id` int(11) NOT NULL COMMENT '曲目课程id',
  `score_id` int(11) NOT NULL COMMENT '曲谱id',
  `record_id` int(11) NOT NULL COMMENT '演奏记录id',
  `is_phrase` TINYINT NOT NULL COMMENT '是否是全曲演奏',
  `phrase_id` int(11) NOT NULL COMMENT '分段',
  `practice_mode` tinyint(4) NOT NULL COMMENT '演奏模式 1正常 2识谱 3慢练',
  `hand` tinyint(4) NOT NULL COMMENT '分手 1左手 2右手 3双手',
  `ui_entry` tinyint(4) NOT NULL COMMENT 'app入口',
  `input_type` tinyint(4) NOT NULL COMMENT '输入源 1midi 2音频',
  `create_time` int(11) NOT NULL,
  `end_time` int(11) DEFAULT NULL COMMENT '演奏结束时间',
  `duration` int(11) DEFAULT NULL COMMENT '时长',
  `audio_url` varchar(255) DEFAULT NULL COMMENT '音频文件',
  `score_final` float DEFAULT NULL COMMENT '总分',
  `score_complete` float DEFAULT NULL COMMENT '分类得分',
  `score_pitch` float DEFAULT NULL COMMENT '分类得分',
  `score_rhythm` float DEFAULT NULL COMMENT '分类得分',
  `score_speed` float DEFAULT NULL COMMENT '分类得分',
  `score_speed_average` float DEFAULT NULL COMMENT '分类得分',
  PRIMARY KEY (`id`)
) COMMENT='ai演奏数据';