INSERT INTO `message_push_rules` (`id`,`name`, `type`, `target`, `is_active`, `time`, `content`, `remark`, `create_time`, `update_time`)
VALUES
 (19,'周周领奖（第1天）', 1, 8, 1, '{\"desc\": \"每周一 19点30分\", \"delay_time\": 0}', '[{\"key\": \"content_1\", \"type\": 1, \"value\": \"\\\\ud83d\\\\ude18小叶子家长您好呀~ \\n \\n❤️温馨提示您本期上传截图领红包活动已经开始啦！ \\n\\\\ud83d\\\\udd34您还有一个红包未领取哦-  \\n \\n<a href=\\\"https://dss-weixin.xiongmaopeilian.com/student/referral?tag=1\\\">>>戳我上传截图，领红包\\\\ud83e\\\\udde7</a>\\n\\n\\\\ud83d\\\\udd25首次参与返现30元 \\n\\\\ud83d\\\\udd25连续不间断参与8期，可得小叶子书包1个 \\n\\\\ud83d\\\\udd25好友扫码您的海报体验，你还可以获得金叶子兑换现金礼品\\n\\n\\\\ud83d\\\\udcac还没有参与活动或未领取红包，速咨询课管老师活动详情\"}]', '', unix_timestamp(), unix_timestamp()),
 (20,'周周领奖（第2天）', 1, 8, 1, '{\"desc\": \"每周二 19点30分\", \"delay_time\": 0}', '[{\"key\": \"content_1\", \"type\": 1, \"value\": \"\\\\ud83d\\\\ude3b今日红包领取通知！  \\n  \\n⚡您的分享红包待领取-  \\n  \\n<a href=\\\"https://dss-weixin.xiongmaopeilian.com/student/referral?tag=1\\\">>>立刻上传，领红包\\\\ud83e\\\\udde7</a>   \\n  \\n活动第2天！火热进行中-  \\n  \\n\\\\ud83d\\\\udd25本月已有28000人成功领取红包\\\\ud83d\\\\udd25  \\n  \\n\\\\ud83d\\\\udca0首次参与返现30元   \\n\\\\ud83d\\\\udca0还没有参与活动或未领取红包，速咨询课管老师活动详情-\"}]', '', unix_timestamp(), unix_timestamp()),
 (21,'周周领奖（第3天）', 1, 8, 1, '{\"desc\": \"每周三 18点\", \"delay_time\": 0}', '[{\"key\": \"content_1\", \"type\": 1, \"value\": \"\\\\ud83d\\\\udcf3幸运用户专属提醒！\\\\ud83d\\\\udcac\\n\\n\\\\ud83c\\\\udf24️您还没有领取本期分享红包\\n<a href=\\\"https://dss-weixin.xiongmaopeilian.com/student/referral?tag=1\\\">点我立即领取>></a>\\n\\n✅参与还可获得金叶子积分\\n✌兑换现金红包\\n✌兑换心仪礼品\\n✌兑换智能强化时长\\n\\n\\\\ud83d\\\\udd25名额有限，请抓紧时间参与\\n\\n<a href=\\\"https://dss-weixin.xiongmaopeilian.com/student/referral?tag=1\\\">\\\\ud83c\\\\udd7e详情点我或咨询课管老师，参与领取-</a>\"}, {\"key\": \"content_2\", \"type\": 1, \"value\": \"宝贝练琴竟不用我费心了？这智能陪练太神奇了！最近老师总夸我家宝贝，其他孩子可羡慕了\\\\ud83d\\\\ude1c，快扫码体验\\\\ud83d\\\\udc47，现在可是孩子的关键期呀！\"}, {\"1\": \"已下线\", \"2\": \"已上线\", \"key\": \"image\", \"QR_X\": \"535\", \"QR_Y\": \"72\", \"type\": 2, \"value\": \"pre/img//auto_push/4c2fda306e04dcbad907cd763741435c.png\", \"QR_WIDTH\": \"154\", \"QR_HEIGHT\": \"154\", \"poster_id\": \"330\", \"POSTER_WIDTH\": \"750\", \"POSTER_HEIGHT\": \"1334\"}]', '', unix_timestamp(), unix_timestamp()),
 (22,'周周领奖（第4天）', 1, 8, 1, '{\"desc\": \"每周四 19点30分\", \"delay_time\": 0}', '[{\"key\": \"content_1\", \"type\": 1, \"value\": \"\\\\ud83d\\\\ude18小叶子家长您好呀~  \\n  \\n\\\\ud83d\\\\udd34您还有一个红包未领取哦-  \\n⛅本期活动倒计时：仅剩4天！ \\n  \\n转发下方文案+海报到朋友圈，保存12小时后，点击下方上传截图即可参与。  \\n  \\n<a href=\\\"https://dss-weixin.xiongmaopeilian.com/student/referral?tag=1\\\">>>戳我上传截图，领红包\\\\ud83e\\\\udde7</a> \\n \\n\\\\ud83d\\\\udd25首次参与返现30元  \\n\\\\ud83d\\\\udd25连续不间断参与8期，可得小叶子书包1个  \\n\\\\ud83d\\\\udd25好友扫码您的海报报名年卡，额外奖励金叶子兑换现金礼品\"}]', '', unix_timestamp(), unix_timestamp()),
 (23,'周周领奖（第5天）', 1, 8, 1, '{\"desc\": \"每周五 19点30分\", \"delay_time\": 0}', '[{\"key\": \"content_1\", \"type\": 1, \"value\": \"\\\\ud83d\\\\udc4b在吗？在吗？快领取本期红包 \\n \\n\\\\ud83d\\\\ude81本期红包领取最后3天！ \\n \\n<a href=\\\"https://dss-weixin.xiongmaopeilian.com/student/referral?tag=1\\\">>>戳我上传截图，领红包\\\\ud83e\\\\udde7</a> \\n \\n\\\\ud83d\\\\udd25已有6W名家长成功领取\\\\ud83d\\\\udd25 \\n \\n\\\\ud83c\\\\udf3c抓紧时间上传领取 \\n\\\\ud83c\\\\udf3c首次参与返现30元 \\n\\\\ud83c\\\\udf3c还没有参与活动或未领取红包，速咨询课管老师活动详情\"}]', '', unix_timestamp(), unix_timestamp()),
 (24,'周周领奖（第6天）', 1, 8, 1, '{\"desc\": \"每周六 16点30分\", \"delay_time\": 0}', '[{\"key\": \"content_1\", \"type\": 1, \"value\": \"\\\\ud83d\\\\udc4b在吗？在吗？未领取红包的小叶子家长快领取本期红包  \\n  \\n\\\\ud83d\\\\ude81本期领取倒计时，最后2天！  \\n  \\n<a href=\\\"https://dss-weixin.xiongmaopeilian.com/student/referral?tag=1\\\">>>戳我上传截图，领红包\\\\ud83e\\\\udde7</a>  \\n  \\n\\\\ud83d\\\\udd25已有8W名家长成功领取\\\\ud83d\\\\udd25  \\n  \\n\\\\ud83c\\\\udf3c抓紧时间上传领取  \\n\\\\ud83c\\\\udf3c首次参与返现30元  \\n\\\\ud83c\\\\udf3c还没有参与活动或未领取红包，速咨询课管老师活动详情\"}]', '', unix_timestamp(), unix_timestamp()),
 (25,'周周领奖（第7天）', 1, 8, 1, '{\"desc\": \"每周天 20点\", \"delay_time\": 0}', '[{\"key\": \"content_1\", \"type\": 1, \"value\": \"\\\\ud83d\\\\ude3b今日红包领取通知！  \\n  \\n⚡您的分享红包待领取-  \\n  \\n<a href=\\\"https://dss-weixin.xiongmaopeilian.com/student/referral?tag=1\\\">>>立刻上传，领红包\\\\ud83e\\\\udde7</a>   \\n  \\n活动今日24:00截止！  \\n  \\n\\\\ud83d\\\\udd25本月已有12W人成功领取红包\\\\ud83d\\\\udd25  \\n  \\n\\\\ud83d\\\\udca0首次参与返现30元   \\n\\\\ud83d\\\\udca0还没有参与活动或未领取红包，速咨询课管老师活动详情-\"}]', '', unix_timestamp(), unix_timestamp()),
 (26,'月月领奖通知1', 1, 8, 1, '{\"desc\": \"每周一 13点\", \"delay_time\": 0}', '[{\"key\": \"content_1\", \"type\": 1, \"value\": \"\\\\ud83c\\\\udf81您的礼物还没有兑换，进入金叶子商城兑换iPhone12⚡！ \\n \\n⌚今日本期活动第一天❣ \\n \\n<a href=\\\"https://referral.xiaoyezi.com/operation/activity/christmas?activity_id=12\\\">>>点我查看活动规则</a> \\n \\n兑iphone12✨兑现金✨兑强化练琴时长 \\n✅一键分享，各种现金礼品随心兑 \\n \\n兑换方式： \\n<a href=\\\"https://dss-weixin.xiongmaopeilian.com/student/myAccount\\\">\\\\ud83c\\\\udf39点我立即兑换</a> \\n\\\\ud83d\\\\udd34如没有参与过活动，可咨询课管老师活动详情，参与领取\"}]', '', unix_timestamp(), unix_timestamp()),
 (27,'月月领奖通知2', 1, 8, 1, '{\"desc\": \"每周三 20点\", \"delay_time\": 0}', '[{\"key\": \"content_1\", \"type\": 1, \"value\": \"\\\\ud83d\\\\ude3b今日最后一次提醒！ \\n \\n您还没有参与活动兑换200元红包\\\\ud83e\\\\udde7 \\n<a href=\\\"https://referral.xiaoyezi.com/operation/activity/christmas?activity_id=12\\\">点我立即参与>></a>\\n \\n\\\\ud83d\\\\udca1还有机会获得： \\n1️⃣ 366天智能时长\\n2️⃣3000元iPadmini5 \\n3️⃣8190元iPhone12\\n \\n<a href=\\\"https://referral.xiaoyezi.com/operation/activity/christmas?activity_id=12\\\">\\\\ud83d\\\\uddfd活动详情可在智能陪练APP查看，或咨询课管老师-</a>\"}]', '', unix_timestamp(), unix_timestamp()),
 (28,'月月领奖通知3', 1, 8, 1, '{\"desc\": \"每周五 10点\", \"delay_time\": 0}', '[{\"key\": \"content_1\", \"type\": 1, \"value\": \"\\\\ud83d\\\\udcf3幸运用户专属提醒！\\\\ud83d\\\\udcac\\n\\n\\\\ud83c\\\\udf24️您还没有领取3000元iPadmini5\\n<a href=\\\"https://referral.xiaoyezi.com/operation/activity/christmas?activity_id=12\\\">点我立即参加>></a>\\n\\n参与还可获得：\\n✌1-8月强化练琴时长\\n✌8190元iPhone12\\n✌The one智能钢琴\\n\\n\\\\ud83d\\\\udd25名额有限，请抓紧时间参与\\n\\n<a href=\\\"https://referral.xiaoyezi.com/operation/activity/christmas?activity_id=12\\\">\\\\ud83c\\\\udd7e详情点我或咨询课管老师，参与领取-</a>\"}]', '', unix_timestamp(), unix_timestamp()),
 (29,'月月领奖通知4', 1, 8, 1, '{\"desc\": \"每周末 19点\", \"delay_time\": 0}', '[{\"key\": \"content_1\", \"type\": 1, \"value\": \"\\\\ud83d\\\\udc9b小叶子提示您：\\n\\n\\\\ud83c\\\\udf39您本月奖励还没有查看哦~\\n\\n<a href=\\\"https://referral.xiaoyezi.com/operation/activity/christmas?activity_id=12\\\">\\\\ud83d\\\\udc49请尽快登录小叶子智能陪练APP领取福利</a>\\n\\n⭕元兑\\n\\\\ud83c\\\\udf81价值3000元iPad mini5\\n\\\\ud83c\\\\udf81APP366天使用时长\\n\\\\ud83c\\\\udf81还可以为宝贝兑换钢琴、iPhone12等\\n\\n<a href=\\\"https://dss-weixin.xiongmaopeilian.com/student/myAccount\\\">\\\\ud83c\\\\udf39点我立即兑换</a>\\n❣奖励详情请打开小叶子智能陪练APP查看-\"}]', '', unix_timestamp(), unix_timestamp());


INSERT INTO `dict` (`type`, `key_name`, `key_code`, `key_value`, `desc`)
VALUES
  ('message_rule_config', '消息推送规则', 'week_reward_mon_rule_id', '19', '周周领奖（第1天）'),
  ('message_rule_config', '消息推送规则', 'week_reward_tue_rule_id', '20', '周周领奖（第2天）'),
  ('message_rule_config', '消息推送规则', 'week_reward_wed_rule_id', '21', '周周领奖（第3天）'),
  ('message_rule_config', '消息推送规则', 'week_reward_thur_rule_id', '22', '周周领奖（第4天）'),
  ('message_rule_config', '消息推送规则', 'week_reward_fri_rule_id', '23', '周周领奖（第5天）'),
  ('message_rule_config', '消息推送规则', 'week_reward_sat_rule_id', '24', '周周领奖（第6天）'),
  ('message_rule_config', '消息推送规则', 'week_reward_sun_rule_id', '25', '周周领奖（第7天）'),
  ('message_rule_config', '消息推送规则', 'month_reward_mon_rule_id', '26', '月月领奖通知1'),
  ('message_rule_config', '消息推送规则', 'month_reward_wed_rule_id', '27', '月月领奖通知1'),
  ('message_rule_config', '消息推送规则', 'month_reward_fri_rule_id', '28', '月月领奖通知1'),
  ('message_rule_config', '消息推送规则', 'month_reward_sun_rule_id', '29', '月月领奖通知1');



