<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
    <title>Admin/Cache</title>
</head>
<body>
<h3><a href="/admin/menu/main">返回</a></h3>
<h2>缓存管理</h2>


<p>Key:</p>
<p><input id="key" type="text" name="cache_key"></p>
<p>Sub Key:</p>
<p><input id="sub_key" type="text" name="cache_sub_key"></p>

<button onclick="fetch('get')">Get</button>
<button onclick="fetch('del')">Clear</button>

<p id="status"></p>

<p>Value:</p>
<p><textarea id="value" name="cache_value" placeholder=""></textarea></p>

<script>
  
  function onError(msg) {
    $('#status').text(msg);
  }

  function fetch(opType) {
    const key = $('#key').val();
    const subKey = $('#sub_key').val();

    const url = '/admin/menu/process?key=cache';
    $.ajax({
      type: "POST",
      url: url,
      data: {
        'cache_key': key,
        'cache_sub_key': subKey,
        'op_type': opType,
      },
      success: function (response) {
        console.log(response);
        if (response.code === 0) {
          let data = response.data;
          if (data.error != null && data.error.length > 0) {
            alert(data.error);
          }
          $('#value').val(JSON.stringify(data.result, null, 4));
        } else {
          $('#value').val(JSON.stringify(response.errors));
        }
      },
      error: function (xhr, ajaxOptions, thrownError) {
        onError(xhr.status + ':' + thrownError);
      }
    });
  }

</script>

</body>
</html>