<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
    <title>Admin/Cache</title>
</head>
<body>
<h3><a href="/admin/menu/main">返回</a></h3>
<h2>设置手机验证码</h2>


<p>手机号码:</p>
<p><input id="key" type="text" name="mobile"></p>
<p>验证码:</p>
<p><input id="sub_key" type="text" name="cache_sub_key"></p>

<button onclick="setCode('get')">Set</button>

<p id="status"></p>

<p>Result:</p>
<p><textarea id="value" name="cache_value" placeholder=""></textarea></p>

<script>
  
  function setMsg(msg) {
    $('#status').text(msg);
  }

  function setCode() {
    const key = $('#key').val();
    const subKey = $('#sub_key').val();

    const url = '/admin/menu/process?key=sms_code';
    $.ajax({
      type: "POST",
      url: url,
      data: {
        'mobile': key,
        'code': subKey,
      },
      success: function (response) {
        setMsg()
        console.log(response);
        if (response.code === 0) {
          let data = response.data;
          if (data.error != null && data.error.length > 0) {
            alert(data.error);
          }
          $('#value').val(JSON.stringify(data.result, null, 4));
        } else {
          $('#value').val(JSON.stringify(response.errors));
        }
      },
      error: function (xhr, ajaxOptions, thrownError) {
        setMsg(xhr.status + ':' + thrownError);
      }
    });
  }

</script>

</body>
</html>